obj-$(CONFIG_PANEL_GENERIC_DPI) += panel-generic-dpi.o
obj-$(CONFIG_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-nl8048hl11-01b.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o

obj-$(CONFIG_PANEL_TC358765) += panel-tc358765.o
obj-$(CONFIG_PANEL_OMAP4_TALOS7) += panel-talos7.o
obj-$(CONFIG_PANEL_OMAP4_TALOS10) += panel-talos10.o

obj-$(CONFIG_PANEL_INNOCOMM_ORACLE) += panel-oracle.o
obj-$(CONFIG_PANEL_INNOCOMM_TC978C) += panel-tc978c.o
obj-$(CONFIG_PANEL_HV070WX1) += panel-hv070wx1.o
obj-$(CONFIG_PANEL_B101EW05) += panel-b101ew05.o
obj-$(CONFIG_PANEL_LS047K1SX01F) += panel-ls047k1sx01f.o
obj-$(CONFIG_PANEL_LS047K1SX01) += panel-ls047k1sx01.o
obj-$(CONFIG_PANEL_BF097XN) += panel-bf097xn.o
